baseURL = "https://whileydave.com/"
languageCode = "en-nz"
title = "Dave's Homepage"
googleAnalytics = "UA-5582165-7"
paginate = 10
enableRobotsTXT = true
summaryLength = 30
PygmentsStyle = "manni"
PygmentsUseClassic = true
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = false

[permalinks]
blog = "/:year/:month/:day/:title/"
