baseURL = "https://whileydave.com/"
languageCode = "en-nz"
title = "Dave's Homepage"
googleAnalytics = "G-9MRLB1FVZX"
paginate = 10
enableRobotsTXT = true
summaryLength = 30

[permalinks]
blog = "/:year/:month/:day/:title/"

[markup.highlight]
noClasses=false
